backend:
  name: git-gateway
  repo: https://gitlab.com/thomas.groch/my-awesome-portfolio
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/.vuepress/public/images"
public_folder: "src/.vuepress/dist/"
collections:
  - label: "Blog" # Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Category, name: category, widget: string}
      - {label: Tags, name: tags, widget: string}
      - {label: "View", name: "view", widget: "hidden", default: "posts"}
      # - {label: "Post tags", name: "tag", widget: "relation", collection: "tags", searchFields: ["name", "twitterHandle"], valueField: "name", displayFields: ["twitterHandle", "followerCount"]
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/sobre/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
